name: dvgt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - attrs==25.4.0
      - bracex==2.6
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - docstring-parser==0.17.0
      - einops==0.8.1
      - embreex==2.17.7.post7
      - filelock==3.20.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - fvcore==0.1.5.post20221221
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - iopath==0.1.10
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lxml==6.0.2
      - manifold3d==3.3.2
      - mapbox-earcut==2.0.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgspec==0.20.0
      - networkx==3.6.1
      - nodeenv==1.10.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - onnxruntime==1.23.2
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pillow==12.0.0
      - plyfile==1.1.3
      - portalocker==3.2.0
      - protobuf==6.33.2
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pycollada==0.9.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rich==14.2.0
      - rpds-py==0.30.0
      - rtree==1.4.1
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scipy==1.16.3
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - svg-path==7.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - tifffile==2025.12.12
      - torch==2.8.0+cu128
      - torchaudio==2.8.0+cu128
      - torchvision==0.23.0+cu128
      - tqdm==4.67.1
      - trimesh==4.10.1
      - triton==3.4.0
      - typeguard==4.4.4
      - typer-slim==0.20.1
      - typing-extensions==4.15.0
      - tyro==1.0.2
      - urllib3==2.6.2
      - vhacdx==0.0.10
      - viser==0.2.23
      - wcmatch==10.1
      - websockets==15.0.1
      - werkzeug==3.1.4
      - xxhash==3.6.0
      - yacs==0.1.8
      - yourdfpy==0.0.58
prefix: /home/lfliang/anaconda3/envs/dvgt
